name: create-release

on:
  push:
    branches:
      - 'release/**' 

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Unshallow
        run: git fetch --prune --unshallow --tags
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Use Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: install github_changelog_generate
        run: gem install github_changelog_generator
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/heads\/release\//}
      - name: Extract branch name
        shell: bash
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}
        id: extract_branch
      - name: create CHANGELOG
        run: make changelog
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: set npm config
        run: npm config set git-tag-version false
      - name: npm version
        run: make release_version_tag
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
          title: release v${{ env.RELEASE_VERSION }}
          body: |
            ## Check List
            - [ ] CHANGELOGの確認
            - [ ] [v${{ env.RELEASE_VERSION }}のdraftリリースノート](https://github.com/ryokosuge/changelog-generator-sample/releases)をpublish

            ### releaseを取り消す場合
            1. [v${{ env.RELEASE_VERSION }}のdraftリリース](https://github.com/ryokosuge/changelog-generator-sample/releases)を削除
            2. このPRを閉じる
            3. ブランチを削除
          labels: release
          base: main
          branch: ${{ env.RELEASE_BRANCH }}
          commit-message: "[ci skip] release v${{ env.RELEASE_VERSION }}"
        env:
          RELEASE_BRANCH: ${{ steps.extract_branch.outputs.BRANCH }}
          RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: Get HEAD Hash
        id: get_last_commit_hash
        run: echo "::set-output name=HASH::$(git rev-parse HEAD)"
      - name: Create Release Note
        run: make release_note
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
          OUTPUT_FILE: release_note.md
      - name: Create Tag & Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ env.RELEASE_TAG_NAME }}
          tag: ${{ env.RELEASE_TAG_NAME }}
          token: ${{ env.GITHUB_TOKEN }}
          commit: ${{ steps.get_last_commit_hash.outputs.HASH }}
          draft: true
          bodyFile: release_note.md
        env:
          RELEASE_TAG_NAME: v${{ steps.get_version.outputs.VERSION }}
