name: create-release

on:
  push:
    branches:
      - 'release/**' 
      - 'fix/release-commit-tag'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Use Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: install github_changelog_generate
        run: gem install github_changelog_generator
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/heads\/release\//}
      - name: Extract branch name
        shell: bash
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}
        id: extract_branch
      - name: create CHANGELOG
        run: make changelog
        env:
          RELEASE_BRANCH: ${{ steps.extract_branch.outputs.BRANCH }}
          # RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
          RELEASE_VERSION: 99.99.00
      - name: set npm config
        run: npm config set git-tag-version false
      - name: npm version
        run: make release_version_tag
        env:
          RELEASE_BRANCH: ${{ steps.extract_branch.outputs.BRANCH }}
          # RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
          RELEASE_VERSION: 99.99.00
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
          title: release v${{ env.RELEASE_VERSION }}
          body: |
            ## Check List
            - [ ] CHANGELOGの確認
            - [ ] [最新のリリースノート](https://github.com/ryokosuge/changelog-generator-sample/releases/tag/v${{ env.RELEASE_VERSION }})に変更内容を追加する
          labels: release
          commit-message: "[ci skip] release v${{ env.RELEASE_VERSION }}"
        env:
          RELEASE_BRANCH: ${{ steps.extract_branch.outputs.BRANCH }}
          # RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
          RELEASE_VERSION: 99.99.00
      - name: Create Tag & Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ env.RELEASE_TAG_NAME }}
          tag: ${{ env.RELEASE_TAG_NAME }}
          token: ${{ env.GITHUB_TOKEN }}
        env:
          RELEASE_BRANCH: ${{ steps.extract_branch.outputs.BRANCH }}
          # RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
          RELEASE_VERSION: 99.99.00
          RELEASE_TAG_NAME: v${{ env.RELEASE_VERSION }}

      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v5.4
      #   with:
      #     github_token: ${{ env.GITHUB_TOKEN }}
      #     release_branches: ${{ env.RELEASE_BRANCH }}
      #     custom_tag: ${{ env.RELEASE_VERSION }}
      #     default_bump: false
      #     create_annotated_tag: true
      #   env:
      #     RELEASE_BRANCH: ${{ steps.extract_branch.outputs.BRANCH }}
      #     RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
      # - name: Create release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     tag_name: ${{ steps.tag_version.outputs.new_tag }}
      # - name: yarn
      #   run: yarn
      # - name: Build
      #   run: yarn build
      # - name: Deploy to Netlify Preview
      #   uses: nwtgck/actions-netlify@v1.1
      #   with:
      #     publish-dir: './build'
      #     production-branch: main
      #     production-deploy: true
      #     enable-pull-request-comment: false
      #     enable-commit-comment: false
      #     enable-commit-status: false
      #     overwrites-pull-request-comment: false
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
