name: push-release-tag

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  push-release-tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    steps:
      - name: output json
        env:
          GITHUB_CONTEX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
