name: push-release-tag

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  push-release-tag:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${HEAD_REF/release\//}
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
      - name: echo VERSION
        run: echo $RELEASE_VERSION
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.4
        with:
          custom_tag: ${{ env.RELEASE_VERSION }}
          github_token: ${{ env.GITHUB_TOKEN }}
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
