name: release

on:
  push:
    branches:
      - 'release/**' 
      - 'feature/github-actions-release'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Use Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: install github_changelog_generate
        run: gem install github_changelog_generator
      - name: Extract branch name
        shell: bash
        run: echo ::set-output name=branch::${GITHUB_REF/refs\/heads\//}
        id: extract_branch
      - name: create CHANGELOG
        run: make changelog
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          RELEASE_VERSION: 1.1.0
      - name: set npm config
        run: npm config set git-tag-version false
      - name: npm version
        run: make release_version_tag
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          RELEASE_VERSION: 1.1.0
      - name: git diff
        run: git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
          title: release
          body: release
          labels: release
          branch: ${{ steps.extract_branch.outputs.branch }}
          base: main
