name: release

on:
  push:
    branches:
      - 'release/**' 
      - 'feature/github-actions-release'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Use Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: install github-changelog-generate
        run: gem install github-changelog-generate
      - name: Extract branch name
        shell: bash
        run: echo ::set-output name=branch::${GITHUB_REF/refs\/heads\//}
        id: extract_branch
      - name: create CHANGELOG
        run: make changelog
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          RELEASE_VERSION: 1.1.0
      - name: git diff
        run: git diff .

