name: release

on:
  push:
    branches:
      - 'release/**' 
      - 'feature/github-actions-release'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Extract branch name
        shell: bash
        run: echo "set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: create CHANGELOG
        uses: heinrichreimer/github-changelog-generator-action@v2
        with:
          user: ryokosuge
          project: changelog-generator-sample
          excludeLabels: release
          token: ${{ env.GITHUB_TOKEN }}
          futureRelease: ${{ env.RELEASE_VERSION }}
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          RELEASE_VERSION: 1.1.0
      - name: git diff
        run: git diff .

